FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    vim \
    curl \
    libsdl1.2-dev \
    libtool \
    libglib2.0-dev \
    libz-dev \
    libpixman-1-dev \
    qemu-kvm \
    git \
 && rm -rf /var/lib/apt/lists/*
